### ISSUE TITLE
[!] (plugin css) Error: ENOENT: no such file or directory, mkdir ''

### ISSUE THREAD

**Issue by Andrew-Opplaud** [thgh/rollup-plugin-css-only#15]
Thank you for creating this plugin. When I add it to `rollup.config.js`:
```
import css from 'rollup-plugin-css-only';
import resolve from 'rollup-plugin-node-resolve';

export default {
  input: 'index.js',
  output: {
    file: 'bundle.js',
    format: 'es',
    sourcemap: true
    }, // output
  plugins: [
    resolve( {
      mainFields: ['module', 'main']
      } ), // resolve()
    css()
    ] // plugins
  }; // export
```
I get:
```
$ node node_modules/.bin/rollup -c

index.js → bundle.js...
[!] (plugin css) Error: ENOENT: no such file or directory, mkdir ''
Error: ENOENT: no such file or directory, mkdir ''

$ 
```
I tried adding `dest:'.'` in various places but that didn't solve it. Help, please?

**Comment by thgh** [comment]
Hmm, it sounds like this line should be conditional
https://github.com/thgh/rollup-plugin-css-only/blob/1a51815f1c34ca01cc25cb5b87cea2f82f543430/src/index.js#L79

**Comment by Andrew-Opplaud** [comment]
Thanks for the response!  I'm not sure how you would make that conditional, but it led me to try a workaround: I changed rollup.config.js to contain:
```
css( { output: './bundle.css' } )
```
In other words, adding a relative path to the output filename stopped mkdir() from throwing the error. Thanks again!
