### ISSUE TITLE
output order is the reverse of what it should be

### ISSUE THREAD

**Issue by Andrew-Opplaud** [thgh/rollup-plugin-css-only#16]
Thank you for creating this plugin.  It does a wonderful job except for one serious issue...

If I have:

    // dependency/index.js
    import './styles.css';
    export default { ... };

    // dependency/styles.css
    .Foo { color: red }

    // project/index.js
    import './styles.css';
    import dependency from 'dependency';
    export default { ... };

    // project/styles.css
    .Foo { color: blue }

then when running rollup in the `project` directory, `<div class=Foo>` will be `red` instead of `blue` because `dependency/styles.css` is appended later in the final stylesheet, as if the HTML contained:

    <link rel=stylesheet href="project/styles.css">
    <link rel=stylesheet href="dependency/styles.css">

However, styles in the project should override styles in the dependency, as if the HTML contained:

    <link rel=stylesheet href="dependency/styles.css">
    <link rel=stylesheet href="project/styles.css">

Can you please correct the order in which stylesheets are concatenated?  Thank you!

**Comment by thgh** [comment]
If somebody knows wether Rollup exposes the order of imports, that would be interesting to solve this issue.
