### ISSUE TITLE
Problem with filter matching when @rollup/pluginutils version 3 is installed

### ISSUE THREAD

**Issue by dimfeld** [thgh/rollup-plugin-css-only#27]
# Situation

I was looking at a problem in the Svelte Discord today that looked similar to https://github.com/sveltejs/template/issues/193, in which the `css-only` plugin appears to not process CSS files emitted by the Svelte rollup plugin.  

Repository here: https://github.com/QuickMick/svelte-getcontext-test. The main package in the repository uses a dependency called `library` which is set to `file:../library` in package.json.

I first noticed that the problem reproduced when I installed dependencies with `npm` (version 6.14.9), but not with `pnpm` (5.13.6), and it seems to be related to the version specifier of `3 || 4`. npm ends up installing version 3 while pnpm ends up using version 4, and the difference is in the implementation of `getMatcherString`.

# Details

Version 4 uses this implementation, where `id` is `"**/*.css"` in this case.
```js
 function getMatcherString(id, resolutionBase) {
    if (resolutionBase === false || path.isAbsolute(id) || id.startsWith('*')) {
        return id;
    }
    // resolve('') is valid and will default to process.cwd()
    const basePath = normalizePath(path.resolve(resolutionBase || ''))
        // escape all possible (posix + win) path characters that might interfere with regex
        .replace(/[-^$*+?.()|[\]{}]/g, '\\$&');
    // Note that we use posix.join because:
    // 1. the basePath has been normalized to use /
    // 2. the incoming glob (id) matcher, also uses /
    // otherwise Node will force backslash (\) on windows
    return path.posix.join(basePath, id);
}
```

Version 3 of pluginutils looks very similar, except that first `if` statement only checks `resolutionBase === false`, and so it does not look for a leading asterisk. So the effect is:

- Version 4 matches a file path against `**/*.css`.
- Version 3 matches a file path against `${process.cwd()}/**/*.css`, which then fails to match anything outside the main directory of the application from which rollup is invoked.

# Proposed Fix

I would suggest changing css-only to depend on `"^4"` of @rollup/pluginutils, though I don't know if there's a good reason to continue allowing v3 to be used. Any thoughts?

**Comment by thgh** [comment]
Makes sense! => v3.1.0 🎉
