### ISSUE TITLE
UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by RobertBColton** [thgh/rollup-plugin-css-only#3]
This occurs when trying to output my css to a ./bin folder. If I create the folder or just run my build script again after it was created I don't get the error.

```javascript
  plugins: [
    vue({styleToImports: true}),
    css({output: './bin/index.css'}),
    resolve()
  ]
```
> (node:17876) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'c:\Users\Owner\Desktop\projects\MyProject\bin\index.css'

Edit: ``rollup-plugin-vue`` added a check for this:
https://github.com/vuejs/rollup-plugin-vue/issues/68

**Comment by namwkim** [comment]
Ditto

**Comment by thgh** [comment]
Call [mkdirp](https://www.npmjs.com/package/mkdirp) just before writing the file would solve this. PR welcome!

**Comment by jukben** [comment]
@thgh It would be great if you deploy a new version with this fix. I would like to use it.

**Comment by foisonocean** [comment]
@thgh  Could you please deploy a new version on NPM with this fix? Thanks

**Comment by thgh** [comment]
There it is! Happy holidays! 🎄
