### ISSUE TITLE
Rollup output.assetFileNames

### ISSUE THREAD

**Issue by moose56** [thgh/rollup-plugin-css-only#30]
Hi,

I am very new to Rollup so apologies if this is a silly question.

Is there a reason Rollup's `output.assetFileNames` is not used for the default output filename of this plug-in?

Is this something that has just not been implemented or is it because `output.assetFileNames` is not for this?

Thanks,

David.

**Comment by thgh** [comment]
It is not yet implemented (assetFileNames didn't exist at the time this was created).

PRs welcome!

**Comment by moose56** [comment]
ok, would you see this as replacing the current behaviour of `output: null`?

Looking at the code that runs when this option is set:

```js
// Guess destination filename
dest =
  opts.file ||
  (Array.isArray(opts.output)
    ? opts.output[0].file
    : opts.output && opts.output.file) ||
  opts.dest ||
  'bundle.js'
if (dest.endsWith('.js')) {
  dest = dest.slice(0, -3)
}
dest = dest + '.css'
```

Using `output.assetFileNames` potentially changes this a lot as it has a default value.

Also is there a plan to continue supporting `opts.dest` as it looks like this is not used in Rollup now?

**Comment by thgh** [comment]
I would suggest to release a major version where dest is not supported and everything works like standard Rollup plugins.

I usually try to have backwards-compatibility as top priority, but `assetFileNames` is just plain better than the current guesswork. So let's go for the most logical behavior and break things where needed.

Looking at create-react-app and others, the default behavior should be to somehow load the css. Some options:

- Append a style tag with the css file contents
- Append a link tag that points to the asset filename

I'm not actively using Rollup for application development anymore, so I'm happy to review stuff, but won't take the lead on this.

**Comment by moose56** [comment]
Ok, will close this and work on raising a PR
