### ISSUE TITLE
Output not outputting any file

### ISSUE THREAD

**Issue by giansegato** [thgh/rollup-plugin-css-only#34]
I'm using the plugin on a Sapper project.

I installed Bulma via `npm`, and imported it in the main `client.js` file like this: `import 'bulma/css/bulma.min.css'`. I then configured my `rollup.config.js` file in the following manner, per documentation:

```javascript
import css from "rollup-plugin-css-only";
// ...
css({output: 'static/bundle.css'}),
//...
```

This doesn't generate any files in the static folder.

However, [using the callback](https://stackoverflow.com/questions/60227236/svelte-css-file-isnt-generate-on-run/66561464#66561464), instead of the regular file definition, works:

```javascript
css({
    output: function (styles, styleNodes) {
        console.log('Writing bundled CSS.');
        fs.writeFileSync('static/bundle.css', styles);
        // this works! a bundle.css file successfully appears in the static folder
    }
})
```

I checked reading-writing permissions in the target folder, but they look fine (also: `writeFileSync` wouldn't be able to write anyway).

**Comment by edward-hong** [comment]
I'm having the same issue, except using the callback method doesn't work either. I'm using the most recent versions of every package. Any help would be appreciated.

**Comment by AlttiRi** [comment]
Yeah, it look passing a filepath does not works.

He replace writing to disk (2.1.0)
```js
import {outputFile} from 'fs-extra/lib/output';
outputFile(dest, css);
```
with (3.1.0)
```js
this.emitFile({type: 'asset', fileName: dest, source: css});
```

**Comment by thgh** [comment]
Could you check if it generates a file in v4? (emitFile is still [skipped](https://github.com/thgh/rollup-plugin-css-only/blob/v4/src/index.mjs#L78) when the file is empty, should it not?)

**Comment by thgh** [comment]
In v4.1.0 emitFile will only be skipped when `output` is a function.
