### ISSUE TITLE
Mention about available @types package in README

### ISSUE THREAD

**Issue by SitamMatt** [thgh/rollup-plugin-css-only#39]
Hi,
I've created types defninition package for this plugin in  [DefinitlyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo.
If you're interested you can mention about that in readme. The package is available [here](https://www.npmjs.com/package/@types/rollup-plugin-css-only).

**Comment by thgh** [comment]
Awesome! Would you like to make a PR to this repo too?
