### ISSUE TITLE
default behaviour: css only being updated if changed

### ISSUE THREAD

**Issue by freshteapot** [thgh/rollup-plugin-css-only#40]
# Short version
I assumed the css was written everytime the ts / js was updated, which is not the case, there is change logic to reduce the css writes.

# Long version
On change in a svelte file, I do some post stuff to the css file, I noticed it was wrong. After digging I learnt that the expected behaviour is to only update the css file if it changes, not everytime. (This issue is made, to give the next person the clue).

# See for yourself
- Set up a project via https://github.com/sveltejs/template
- Modify rollup to use function for css output
```js
css({
    output: function (styles, styleNodes) {
        console.log("HERE", styles);
        fs.writeFileSync('bundle.css', styles)
    },
}),
```
- Run via
```sh
npm run dev
```
- Observe "HERE"
- Modify App.svelte (but not the style block)
- Observe file change but "HERE" is not there.
- Look in the generateBundle function and you will see a !change protection.

**Comment by freshteapot** [comment]
I note https://github.com/thgh/rollup-plugin-css-only/pull/37

**Comment by thgh** [comment]
The change detection has been removed in v4
