### ISSUE TITLE
Unexpected behavior with no css imports or empty imports in 4.1.0

### ISSUE THREAD

**Issue by WhizzoCode** [thgh/rollup-plugin-css-only#47]
**In rollup-plugin-css-only 3.1.0:**

- If there are not css imports, no `bundle.css` is generated.
- Doing `import './style.css'`, if `./style.css` is an empty file, no `bundle.css` is generated.

**In rollup-plugin-css-only 4.1.0:**

- If there are not css imports, an empty `bundle.css` is generated.
- Doing `import './style.css'`, if `./style.css` is an empty file, a `bundle.css` is generated, containing the string `undefined\n`.

**Comment by thgh** [comment]
I feel that is more an issue with Rollup as this plugin is actually emitting the asset, but let's just fix it anyway:

Released v4.1.1 that always adds an empty line 🎉
