### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'importedIds')

### ISSUE THREAD

**Issue by linyxria** [thgh/rollup-plugin-css-only#48]
getModuleInfo(id).importedIds.forEach(function (importId) {
      modules = new Set(
        [].concat(
          Array.from(modules),
          Array.from(getCSSModules(importId, getModuleInfo, modules))
        )
      );
    })

My rollup plugins configuration is as follows:

plugins: [
      peerDepsExternal(),
      resolve(),
      commonjs(),
      typescript({ tsconfig: './tsconfig.json' }),
      linaria({
        sourceMap: true,
        babelOptions: {
          presets: ['@babel/preset-typescript', '@babel/preset-react'],
        },
      }),
      css({
        output: 'styles.css',
      }),
    ]

**Comment by terrywh** [comment]
![image](https://user-images.githubusercontent.com/968222/197549292-a001e776-3fe7-4fcb-bf95-4fa0f2c64bc9.png)

same here (after rollup update)

**Comment by thgh** [comment]
Not exactly sure what causes this, but a fix has been published in v4.2

Feel free to reopen and add a reproducible demo repo
