### ISSUE TITLE
Unreasonably long bundling time after updating rollup-plugin-css-only from 3.1.0 to 4.2.0

### ISSUE THREAD

**Issue by Snailedlt** [thgh/rollup-plugin-css-only#49]
Hi, we're using this project in a government project written in svelte. After updating rollup-plugin-css-only from 3.1.0 to 4.2.0 we're experiencing a significant increase in the bundling time.

After running `npm i` and `npm run dev` with the following setup `"dev": "rollup -c -w"`, it runs in 5min instead of 12 seconds. The same happens with `npm run build` with the following setup `"build": "rollup -c"`

The only changes done were to package.json and package-lock.json (PR by dependabot), so we are sure the issue is with this plugin, but not sure exactly what the issue is.

Before updating: `12.2s`
![image](https://user-images.githubusercontent.com/43886029/198556585-a52e33ab-84c8-4e7b-a1c7-6081a0a39f91.png)

After updating: `5m 16s`
![image](https://user-images.githubusercontent.com/43886029/198556623-86bf6f68-fd2d-4cdd-afd6-748dce3da0c9.png)

The project is private, so I can't share much, but here's some config files we use, which may or may not be relevant:
[project_config_files.zip](https://github.com/thgh/rollup-plugin-css-only/files/9887346/project_config_files.zip)

Let me know if you need any more info, and I'll try to provide it quickly

**Comment by thgh** [comment]
Interesting that dependabot suggests major upgrades. I could release a minor upgrade to v3 with only rollup 3 support?

**Comment by Snailedlt** [comment]
Does that mean it should not have suggested that update to us? If so, why not... and do you know why bundling takes so long?

**Comment by Snailedlt** [comment]
Also I see v4 brought some breaking changes, but couldn't find any info on what needs to be changed in order to make it work again. Is the migration process documented anywhere?

**Comment by thgh** [comment]
To be honest, I'm not using this module/Rollup anymore. The main change is that you should replace the output option with the name or filename option.

**Comment by Snailedlt** [comment]
Ahh, okey :)
You're talking about this then, right? :)
`css({ output: 'bundle.css' })`

Should it be replaced with this?
`css({ filename: 'bundle.css' })`

**Comment by nikolas** [comment]
I ran into this problem, too. Downgrading to version 3.1.x fixed the problem. https://github.com/ccnmtl/mathplayground/pull/90

**Comment by nikolas** [comment]
Using the new version (4.2.0), `css({ filename: 'bundle.css' })` doesn't seem to fix the problem, either. I think I will just stick with the old version.

**Comment by thgh** [comment]
Using v3 is fine, v4 is just there because Rollup provided a new API that may be more powerful.
